sudo: required
language: node_js
node_js:
   - "8"
install:
    - npm install
    - npm install -g http-server
    - npm install node-fetch
    - npm install -g mocha

before_script:
  - rm routes.json
  - mv test/routes.json routes.json
  -
  - sleep 5
  - export SECRET="camic"
  - export PORT=4010

script:
- cd test && http-server -s -p 8000 && cd ../
- npm start &
- sleep 10
- npm test
