sudo: required
language: node_js
node_js:
   - "8"
install:
    - npm install
    - npm install -g http-server
    - npm install node-fetch

before_script:
  - rm routes.json
  - mv test/routes.json routes.json
  - http-server -s -p 8000 &
  - export SECRET="camic"
  - node elevate.js &

script:
- mocha test/test_router.js --exit
